- name: gopls
  community.general.pacman:
    name:
      - gopls
  tags:
    - install
    - core
    - neovim
    - lsp

- name: lua language server (clone)
  ansible.builtin.git:
    repo: "https://github.com/sumneko/lua-language-server"
    dest: "{{ lookup('env', 'HOME') }}/personal/lua-language-server"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - core
    - neovim
    - lsp
# - name: lua language server (setup)
#   shell: cd /home/yoni/personal/lua-language-server && git submodule update --init --recursive
#   shell: /home/yoni/personal/lua-language-server/3rd/luamake/compile/install.sh && /home/yoni/personal/lua-language-server/3rd/luamake/compile/rebuild
#   tags:
#     - install
#     - core
#     - neovim
#     - lsp

- name: pyright
  shell: sudo pip3 install pyright
  tags:
    - install
    - core
    - neovim
    - lsp

- name: rust analyzer
  community.general.pacman:
    name:
      - rust-analyzer
  tags:
    - install
    - core
    - neovim
    - lsp
