- name: todo me daddy exists
  stat:
    path: "/home/yoni/personal/todo-me-daddy"
  register: tdm
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project
- name: Personal Project todo-me-daddy
  ansible.builtin.git:
    repo: 'https://github.com/yonikosiner/todo-me-daddy'
    bare: true
    dest: "/home/yoni/personal/todo-me-daddy"
  tags:
    - install
    - personal-project
    - neovim
    - dotfiles
- name: todo-me-daddy checkout master
  shell: cd ~/personal/todo-me-daddy && git worktree add master master
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project
  when: tdm.stat.exists == False

- name: Twitch bot exists
  stat:
    path: "/home/yoni/personal/twitch-bot"
  register: twitchbot
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project
- name: Personal Project twitch bot
  ansible.builtin.git:
    repo: 'https://github.com/yonikosiner/Twitch_bot'
    bare: true
    dest: "/home/yoni/personal/twitch-bot"
  tags:
    - install
    - personal-project
    - neovim
    - dotfiles
  when: twitchbot.stat.exists == False
- name: twitch bot checkout ui
  shell: cd ~/personal/twitch-bot && git worktree add ui ui
  tags:
    - install
    - dotfiles
    - neovim
    - personal-project
  when: twItchbot.stat.exists == False

- name: yonikosiner-com exists
  stat:
    path: "/home/yoni/personal/yonikosiner-com/"
  register: yonikosiner-com
  tags:
    - install
    - personal-project
- name: Personal Project yonikosiner-com
  ansible.builtin.git:
    repo: 'https://github.com/yonikosiner/yonikosiner-com'
    bare: true
    dest: "/home/yoni/personal/yonikosiner-com"
  tags:
    - install
    - personal-project
  when: yonikosiner-com.stat.exists == False
- name:  yonikosiner checkout master
  shell: cd ~/personal/yonikosiner-com && git worktree add master master
  tags:
    - install
    - personal-project
  when: yonikosiner-com.stat.exists == False

- name: go wiki exists
  stat:
    path: "/home/yoni/personal/gowiki/"
  register: gowiki
  tags:
    - install
    - personal-project
- name: Personal Project gowiki
  ansible.builtin.git:
    repo: 'https://github.com/yonikosiner/gowiki'
    bare: true
    dest: "/home/yoni/personal/gowiki"
  tags:
    - install
    - personal-project
  when: gowiki.stat.exists == False
- name:  gowiki checkout master
  shell: cd ~/personal/gowiki && git worktree add master master
  tags:
    - install
    - personal-project
  when: gowiki.stat.exists == False
