- name: Install ZSH
  community.general.pacman: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]

- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags: *tags_for_zsh_tasks

- name: Check that the somefile.conf exists
  stat:
    path: /home/yoni/.oh-my-zsh
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags: *tags_for_zsh_tasks
  when: oh_my_stats.stat.exists == False
  become_user: yoni

- name: Install zsh-fzf-history-search
  ansible.builtin.git:
    repo: 'https://github.com/joshskidmore/zsh-fzf-history-search'
    dest: "~/.oh-my-zsh/plugins/zsh-fzf-history-search"
  tags: *tags_for_zsh_tasks

- name: Install fzf-zsh-completion
  ansible.builtin.git:
    repo: 'https://github.com/lincheney/fzf-tab-completion'
    dest: "~/personal/fzf-tab-completion"
  tags: *tags_for_zsh_tasks
